services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8081:80"
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mysql:8.1
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: laravel_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  db_data:
